# Generated by Django 5.1.15 on 2026-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='accepted_payments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='villa',
            name='build_up_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='villa',
            name='payout_account',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
