# Generated by Django 5.1.15 on 2026-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_responded',
            field=models.BooleanField(default=False),
        ),
    ]
