# Generated by Django 5.1.15 on 2026-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
