# Generated by Django 5.1.15 on 2026-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_booking_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='additional_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='events_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villa',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villa',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
