# Generated by Django 5.1.15 on 2026-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_villa_house_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='bathrooms',
        ),
        migrations.AddField(
            model_name='villa',
            name='double_bed_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villa',
            name='single_bed_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
