# Generated by Django 5.1.15 on 2026-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_villa_rooms_and_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='max_stay_nights',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
