# Generated by Django 5.1.15 on 2026-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_villa_max_stay_nights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='max_stay_nights',
        ),
        migrations.AddField(
            model_name='villa',
            name='availability_days',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
