# Generated by Django 5.1.15 on 2026-07-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_villa_availability_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='properties.villa')),
            ],
            options={
                'db_table': 'properties_villa_blocked_date',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('villa', 'date'), name='uniq_blocked_villa_date')],
            },
        ),
    ]
