# Generated by Django 5.1.15 on 2026-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_booking_coupon_code_booking_discount_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='host_responded',
        ),
    ]
