# Generated by Django 5.1.15 on 2026-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_booking_checked_in_at_booking_checked_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='villa',
            name='extra_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
