# Generated by Django 5.1.15 on 2026-07-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_booking_cancellation_fee_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='villa_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='villa_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='villa_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
