# Generated by Django 5.1.15 on 2026-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
