# Generated by Django 5.1.15 on 2026-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_coupon_valid_from_coupon_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='villa',
            name='payout_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='villa',
            name='payout_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
