# Generated by Django 5.1.15 on 2026-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_villa_payout_account_name_villa_payout_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villaimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='villaimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
