# Generated by Django 5.1.15 on 2026-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_villaimage_options_villaimage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_booking_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villaimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
