# Generated by Django 5.1.15 on 2026-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_booking_first_booking_discount_villaimage_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
