# Generated by Django 5.1.15 on 2026-07-29 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_booking_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_check_in_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.CreateModel(
            name='CheckInVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_verifications', to='properties.booking')),
            ],
            options={
                'db_table': 'properties_checkin_verification',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['booking', '-generated_at'], name='properties__booking_934eda_idx')],
            },
        ),
    ]
