# Generated by Django 5.1.15 on 2026-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_booking_grace_period_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_notes',
            field=models.TextField(blank=True),
        ),
    ]
