# Generated by Django 5.1.15 on 2026-07-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_stayhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='segment_stays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
