# Generated by Django 5.1.15 on 2026-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_booking_segment_stays'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='released_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkinverification',
            name='purpose',
            field=models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out')], default='check_in', max_length=16),
        ),
    ]
