# Generated by Django 5.1.15 on 2026-08-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_booking_released_nights_checkinverification_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('full', 'Whole booking'), ('partial', 'Selected nights')], default='partial', max_length=12)),
                ('nights', models.JSONField(blank=True, default=list)),
                ('nights_count', models.PositiveIntegerField(default=0)),
                ('stay_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_percentage', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='properties.booking')),
            ],
            options={
                'db_table': 'properties_bookingcancellation',
                'ordering': ['created_at'],
            },
        ),
    ]
