# Generated by Django 5.1.15 on 2026-08-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_booking_checked_in_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('services', 'Extra services'), ('nights', 'Extra nights')], default='services', max_length=12)),
                ('services', models.JSONField(blank=True, default=list)),
                ('nights', models.JSONField(blank=True, default=list)),
                ('nights_count', models.PositiveIntegerField(default=0)),
                ('accommodation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('payment_reference', models.CharField(blank=True, max_length=24)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='properties.booking')),
            ],
            options={
                'db_table': 'properties_bookingaddition',
                'ordering': ['created_at'],
            },
        ),
    ]
