# Generated by Django 5.1.15 on 2026-08-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_booking_forced_check_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingaddition',
            name='kind',
            field=models.CharField(choices=[('services', 'Extra services'), ('nights', 'Extra nights'), ('both', 'Nights and services')], default='services', max_length=12),
        ),
    ]
