# Generated by Django 5.1.15 on 2026-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_bookingaddition_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcancellation',
            name='extras_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
