# Generated by Django 5.1.15 on 2026-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_bookingcancellation_extras_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcancellation',
            name='kind',
            field=models.CharField(choices=[('full', 'Whole booking'), ('partial', 'Selected nights'), ('services', 'Extra services')], default='partial', max_length=12),
        ),
    ]
