# Generated by Django 5.1.15 on 2026-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_bookingcancellation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcancellation',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
