# Generated by Django 5.1.15 on 2026-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_bookingcancellation_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
