# Generated by Django 5.1.15 on 2026-08-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_villa_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='late_check_in_allowed',
        ),
    ]
